### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by akamming** [wandera/1password-client#49]
**Describe the bug**
error in the code?  I tried the sample code, and i got this typerror in the library

**To Reproduce**
- on a pretty clean raspberyy pi 4B  (Bullseye, with  sudo apt update/upgrade)
- i installed the library with pip install 1password
- then i ran the sample code:
```
from onepassword import OnePassword
import json

op = OnePassword()

# List all vaults 
json.loads(op.list_vaults())

# List all items in a vault, default is Private
op.list_items()

# Get all fields, one field or more fields for an item with uuid="example"
op.get_item(uuid="example")
op.get_item(uuid="example", fields="username")
op.get_item(uuid="example", fields=["username", "password"])`
```
and got this error:
```
pi@studeerkamer:~/1pw $ python3 backup.py
Traceback (most recent call last):
  File "/home/pi/1pw/backup.py", line 1, in <module>
    from onepassword import OnePassword
  File "/home/pi/.local/lib/python3.9/site-packages/onepassword/__init__.py", line 1, in <module>
    from .client import OnePassword
  File "/home/pi/.local/lib/python3.9/site-packages/onepassword/client.py", line 10, in <module>
    from onepassword.utils import read_bash_return, domain_from_email, Encryption, BashProfile, get_device_uuid, \
  File "/home/pi/.local/lib/python3.9/site-packages/onepassword/utils.py", line 64, in <module>
    def _spawn_signin(command, m_password) -> str | bool:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

```

So already fails on the "from onepassword import OnePassword" line...

**Expected behavior**
At least to not fail on the "from onepassword import OnePassword" line

**Desktop (please complete the following information):**
 - OS: rapsberry pi bullseye

**Comment by dtpryce** [comment]
Hey @akamming thanks for posting this issue ... it looks like you are using python 3.9 and this might be where the issue is arising. For security patching and regulatory use we have to keep our python version fairly up to date and so have implemented this library for 3.10 and higher, are you able to use this version of python?

**Comment by akamming** [comment]
I am indeed on python 3.9 which is the default python for the rpi bullseye distribution. I Will check if I can upgrade easily

**Comment by dale-courtney** [comment]
Hey, team. 
I'm running Python 3.11.6
When I run the following: 

```
from onepassword import OnePassword
import json

op = OnePassword()

json.loads(op.list_vaults())
```
I get the error: 
`TypeError: the JSON object must be str, bytes or bytearray, not list`

op.list_vaults() function is returning a list instead of a string. The json.loads() function expects a JSON-formatted string as input.

When I changed the code to: 
```
vaults_json = json.dumps(op.list_vaults())
vaults_data = json.loads(vaults_json)
```

I do get valid vaults_data back. However, I only get back 13 vaults. I have >100 vaults in my account. 

Any idea why? 

Thanks in advance. 
Best,
Dale

**Comment by dtpryce** [comment]
> I am indeed on python 3.9 which is the default python for the rpi bullseye distribution. I Will check if I can upgrade easily

How did this go?

**Comment by dtpryce** [comment]
> Hey, team. I'm running Python 3.11.6 When I run the following:
> 
> ```
> from onepassword import OnePassword
> import json
> 
> op = OnePassword()
> 
> json.loads(op.list_vaults())
> ```
> 
> I get the error: `TypeError: the JSON object must be str, bytes or bytearray, not list`
> 
> op.list_vaults() function is returning a list instead of a string. The json.loads() function expects a JSON-formatted string as input.
> 
> When I changed the code to:
> 
> ```
> vaults_json = json.dumps(op.list_vaults())
> vaults_data = json.loads(vaults_json)
> ```
> 
> I do get valid vaults_data back. However, I only get back 13 vaults. I have >100 vaults in my account.
> 
> Any idea why?
> 
> Thanks in advance. Best, Dale

@dale-courtney I have moved this into a separate issue https://github.com/wandera/1password-client/issues/55
